SCHOOLS = [
'University of California Berkeley',
'University of California Davis',
'Arizona State University Tempe',
'Boston College',
'Boston University',
'Brandeis University',
'Brown University',
'California Institute of Technology',
'Carnegie Mellon University',
'Case Western Reserve University',
'Clemson University',
'Colorado State University Fort Collins',
'Columbia University in the City of New York',
'Cornell University',
'CUNY Graduate School and University Center',
'Duke University',
'Emory University',
'Florida International University',
'Florida State University',
'George Mason University',
'George Washington University',
'Georgetown University',
'Georgia Institute of Technology',
'Georgia State University',
'Harvard University',
'Indiana University Bloomington',
'Iowa State University',
'Johns Hopkins University',
'Kansas State University',
'Louisiana State University and Agricultural & Mechanical College',
'Massachusetts Institute of Technology',
'Michigan State University',
'New York University',
'North Carolina State University',
'Northeastern University',
'Northwestern University',
'Ohio State University',
'Oregon State University',
'Pennsylvania State University Main Campus',
'Princeton University',
'Purdue University Main Campus',
'Rice University',
'Rutgers University New Brunswick',
'Stanford University',
'Stony Brook University',
'SUNY at Albany',
'Syracuse University',
'Temple University',
'Texas A&M University',
'Texas Tech University',
'Tufts University',
'Tulane University of Louisiana',
'University at Buffalo',
'University of Alabama at Birmingham',
'University of Arizona',
'University of Arkansas',
'University of California Irvine',
'University of California Los Angeles',
'University of California Riverside',
'University of California San Diego',
'University of California Santa Barbara',
'University of California Santa Cruz',
'University of Central Florida',
'University of Chicago',
'University of Cincinnati Main Campus',
'University of Colorado Boulder',
'University of Connecticut',
'University of Delaware',
'University of Florida',
'University of Georgia',
'University of Hawaii at Manoa',
'University of Houston',
'University of Illinois at Chicago',
'University of Illinois at Urbana Champaign',
'University of Iowa',
'University of Kansas',
'University of Kentucky',
'University of Louisville',
'University of Maryland College Park',
'University of Massachusetts Amherst',
'University of Miami',
'University of Michigan Ann Arbor',
'University of Minnesota Twin Cities',
'University of Mississippi',
'University of Missouri Columbia',
'University of Nebraska Lincoln',
'University of New Mexico Main Campus',
'University of North Carolina at Chapel Hill',
'University of North Texas',
'University of Notre Dame',
'University of Oklahoma Norman Campus',
'University of Oregon',
'University of Pennsylvania',
'University of Pittsburgh Pittsburgh Campus',
'University of Rochester',
'University of South Carolina Columbia',
'University of South Florida Main Campus',
'University of Southern California',
'University of Tennessee',
'University of Texas at Arlington',
'University of Texas at Austin',
'University of Texas at Dallas',
'University of Utah',
'University of Virginia Main Campus',
'University of Washington Seattle Campus',
'University of Wisconsin Madison',
'University of Wisconsin Milwaukee',
'Vanderbilt University',
'Virginia Commonwealth University',
'Virginia Polytechnic Institute and State University',
'Washington State University',
'Washington University in St Louis',
'Wayne State University',
'West Virginia University',
'Yale University',
'American University',
'Auburn University',
'Augusta University',
'Ball State University',
'Baylor University',
'Bowling Green State University Main Campus',
'Brigham Young University Provo',
'Catholic University of America',
'Central Michigan University',
'Claremont Graduate University',
'Clark Atlanta University',
'Cleveland State University',
'College of William and Mary',
'Colorado School of Mines',
'Dartmouth College',
'Drexel University',
'Duquesne University',
'East Carolina University',
'Florida Agricultural and Mechanical University',
'Florida Atlantic University',
'Florida Institute of Technology',
'Fordham University',
'Howard University',
'Illinois Institute of Technology',
'Illinois State University',
'Indiana University Purdue University Indianapolis',
'Jackson State University',
'Kent State University at Kent',
'Lehigh University',
'Loyola University Chicago',
'Marquette University',
'Miami University Oxford',
'Michigan Technological University',
'Mississippi State University',
'Missouri University of Science and Technology',
'Montana State University',
'Naval Postgraduate School',
'New Jersey Institute of Technology',
'New Mexico State University Main Campus',
'North Carolina A & T State University',
'North Dakota State University Main Campus',
'Northern Arizona University',
'Northern Illinois University',
'Nova Southeastern University',
'Ohio University Main Campus',
'Oklahoma State University Main Campus',
'Old Dominion University',
'Portland State University',
'Rensselaer Polytechnic Institute',
'Rockefeller University',
'Rutgers University Newark',
'Saint Louis University',
'San Diego State University',
'South Dakota State University',
'Southern Illinois University Carbondale',
'Southern Methodist University',
'Stevens Institute of Technology',
'SUNY at Binghamton',
'Teachers College at Columbia University',
'Texas A&M University Commerce',
'Texas Christian University',
'Texas State University',
'The New School',
'University of Alabama',
'University of Texas at El Paso',
'University of Texas at San Antonio',
'University of Akron Main Campus',
'University of Alabama in Huntsville',
'University of Alaska Fairbanks',
'University of California Merced',
'University of Colorado Denver',
'University of Dayton',
'University of Denver',
'University of Idaho',
'University of Louisiana at Lafayette',
'University of Maine',
'University of Maryland Baltimore County',
'University of Massachusetts Boston',
'University of Massachusetts Dartmouth',
'University of Massachusetts Lowell',
'University of Memphis',
'University of Missouri Kansas City',
'University of Missouri St Louis',
'University of Montana',
'University of Nevada Las Vegas',
'University of Nevada Reno',
'University of New Hampshire Main Campus',
'University of New Orleans',
'University of North Carolina at Charlotte',
'University of North Carolina at Greensboro',
'University of North Dakota',
'University of Northern Colorado',
'University of Puerto Rico Rio Piedras',
'University of Rhode Island',
'University of South Alabama',
'University of South Dakota',
'University of Southern Mississippi',
'University of Toledo',
'University of Tulsa',
'University of Vermont',
'University of Wyoming',
'Utah State University',
'Wake Forest University',
'Western Michigan University',
'Wichita State University',
'Worcester Polytechnic Institute',
'Yeshiva University',
'Universities classified as "R3: Doctoral Universities – Moderate Research Activity"[edit]',
'There are 113 institutions classified as "Doctoral Universities – Moderate Research Activity" in the Carnegie Classification [4]. These institutions carry out research, but not to the extent of high or very high research activity institutions.',
'Doctoral Universities – Limited Research Activity',
'Institution Control CityState',
'Adelphi University',
'Air Force Institute of Technology',
'Alliant International University San Diego',
'American International College',
'Andrews University',
'Argosy University Atlanta',
'Argosy University Chicago',
'Argosy University Denver',
'Argosy University Inland Empire',
'Argosy University Orange County',
'Argosy University Phoenix Online Division',
'Argosy University Sarasota',
'Argosy University Tampa',
'Arizona State University Downtown Phoenix',
'Arizona State University Skysong',
'Ashland University',
'Aspen University',
'Azusa Pacific University',
'Barry University',
'Benedictine University',
'Biola University',
'Boise State University',
'California Institute of Integral Studies',
'California State University Fresno',
'California State University Fullerton',
'Capella University',
'Cardinal Stritch University',
'Clark University',
'Clarkson University',
'Dallas Baptist University',
'DePaul University',
'Drew University',
'East Tennessee State University',
'Eastern Michigan University',
'Edgewood College',
'Fairleigh Dickinson University Metropolitan Campus',
'Fielding Graduate University',
'Gardner Webb University',
'Georgia Southern University',
'Grand Canyon University',
'Hofstra University',
'Idaho State University',
'Immaculata University',
'Indiana State University',
'Indiana University of Pennsylvania Main Campus',
'Inter American University of Puerto Rico Metro',
'Kennesaw State University',
'Lamar University',
'Lesley University',
'Liberty University',
'Lindenwood University',
'Lipscomb University',
'Louisiana Tech University',
'Maryville University of Saint Louis',
'Mercer University',
'Middle Tennessee State University',
'Montclair State University',
'Morgan State University',
'National Louis University',
'Northcentral University',
'Oakland University',
'Pepperdine University',
'Pontifical Catholic University of Puerto Rico Ponce',
'Prairie View A&M University',
'Regent University',
'Robert Morris University',
'Rochester Institute of Technology',
'Saint John Fisher College',
'Sam Houston State University',
'San Francisco State University',
'Seattle Pacific University',
'Seton Hall University',
'Shenandoah University',
'Spalding University',
'St John\'s University New York',
'Suffolk University',
'SUNY College of Environmental Science and Forestry',
'Tennessee State University',
'Tennessee Technological University',
'Texas A&M University Corpus Christi',
'Texas A&M University Kingsville',
'Texas Southern University',
'Texas Wesleyan University',
'Texas Woman\'s University',
'University of Texas – Rio Grande Valley',
'University of West Florida',
'Trevecca Nazarene University',
'Trident University International',
'Trinity International University Illinois',
'Union Institute & University',
'Union University',
'Universidad del Turabo',
'University of Arkansas at Little Rock',
'University of Hartford',
'University of La Verne',
'University of Louisiana at Monroe',
'University of Management and Technology',
'University of Maryland Eastern Shore',
'University of Nebraska at Omaha',
'University of Phoenix Arizona',
'University of San Diego',
'University of San Francisco',
'University of St Thomas Saint Paul',
'University of the Cumberlands',
'University of the Pacific',
'University of West Georgia',
'Valdosta State University',
'Villanova University',
'Walden University',
'Widener University Main Campus',
'Wilmington University',
'Wright State University Main Campus']

SCHOOLS = [{'code': name.lower().replace(' ', ' '), 'name': name} for name in SCHOOLS]